### ISSUE TITLE
Check if black is in check?

### ISSUE THREAD

**Issue by MonliH** [romstad/Chess.jl#19]
Hello, I am currently trying to use this library to solve a variant of chess. However, the `ischeck` function doesn't seem to work in some positions where black is in check, even though I've used `donullmove`. For some reason I have to change the board into an FEN and convert back after performing the null move for it to work properly:

```julia
julia> board  = fromfen("1q2n2n/ppprkprr/1pp3pp/8/8/PPPP3P/BP2RQPB/R2BK2N w - - 0 1")
Board (1q2n2n/ppprkprr/1pp3pp/8/8/PPPP3P/BP2RQPB/R2BK2N w - -):
 -  q  -  -  n  -  -  n 
 p  p  p  r  k  p  r  r 
 -  p  p  -  -  -  p  p 
 -  -  -  -  -  -  -  - 
 -  -  -  -  -  -  -  - 
 P  P  P  P  -  -  -  P 
 B  P  -  -  R  Q  P  B 
 R  -  -  B  K  -  -  N 

julia> ischeck(board)
false

julia> ischeck(donullmove(board))   # should be true
false

julia> donullmove(board)
Board (1q2n2n/ppprkprr/1pp3pp/8/8/PPPP3P/BP2RQPB/R2BK2N b - -):
 -  q  -  -  n  -  -  n 
 p  p  p  r  k  p  r  r 
 -  p  p  -  -  -  p  p 
 -  -  -  -  -  -  -  - 
 -  -  -  -  -  -  -  - 
 P  P  P  P  -  -  -  P 
 B  P  -  -  R  Q  P  B 
 R  -  -  B  K  -  -  N 

# ^ This FEN is definitely a check, what's wrong??

julia> ischeck(fromfen(fen(donullmove(board))))  # why does this work?
true
```

There is certainly a check:
<img width=400 src="https://user-images.githubusercontent.com/30177086/133940527-2bc12d1e-ab94-4753-8289-0aca27e7307a.png"></img>

How can I check if black is in check properly? The workaround works for me, but doesn't seem like the proper way to do this. The problem (without looking at the internal code) is probably that the `checkers` bit-board isn't updated on a `donullmove` (maybe a call to `findcheckers` in that function would help?).

**Comment by romstad** [comment]
The reason why this happens is that the board position in your first call to `fromfen` is illegal (in standard chess, that is): The side to move can capture the king, which means that the position cannot possibly occur through a sequence of legal moves.

Calling `findcheckers` in `donullmove` would probably fix your problem, but I don't want to do that, because it's an expensive operation, and also an unnecessary one for standard chess, because the position after a null move in a legal chess position can _never_ be check.

You could try manually calling `findcheckers` after `donullmove`, and see if that is an acceptable solution to you, but I think there's a significant risk that you will encounter other issues if you try to use this library as is for non-standard chess variants. For instance, I'm fairly sure that positions where both kings are in check, where there are more than two checking pieces, and where there are not exactly one king for each side will not be handled correctly.

Perhaps the best solution in your case is to fork the library and adapt it to your needs.

**Comment by MonliH** [comment]
As I see, thank you for the thoughtful response. For now, I'll just use `findcheckers` and I'll consider forking later on.
